services:
  todo_mysql:
    image: mysql:8.4.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: to_do
    ports:
      - "53306:3306"
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db-schema.sql:/docker-entrypoint-initdb.d/db-schema.sql
